### ISSUE TITLE
Browser not loading

### ISSUE THREAD

**Issue by adecker794** [nurdism/neko#19] opened 2020-01-24 03:16 UTC
I have installed neko, I was able to open it in Firefox, but once I am logged in, the browser does not pop up. I thought I had to install to firefox so I did that and still a black box, even after a reboot. Maybe I am missing something? I have the emojis and the chat, the settings in the top right are there. I am running on a ubuntu-server 16.04 VM.

**Comment by nurdism** [comment] 2020-01-24 05:08
dupe of #14

**Closed as completed by nurdism** 2020-01-24 05:08 UTC

**Comment by esinanturan** [comment] 2020-01-31 12:16
I am having the same issue, application starts but it has black screen casting doesn't work on both chrome and firefox
